In [33]:
import pandas as pd

In [34]:
outlets = pd.read_csv("Data/QSR_outlet_dataset_cleaned.csv", keep_default_na=False)
socioeconomic = pd.read_csv("Data/QSR_socioeconomic_dataset_cleaned.csv")

In [35]:
outlets.shape

(2816, 17)

In [36]:
socioeconomic.shape

(20, 9)

In [37]:
outlets.columns

Index(['Outlet ID', 'Brand', 'Region', 'Province', 'Province_Shorthand',
       'City', 'Menu_Category', 'Price_Range', 'Customer_Rating',
       'Review_Count', 'Latitude', 'Longitude', 'Location_Type', 'Address',
       'Source', 'Price_Range_Cleaned', 'Price_Range_Imputed'],
      dtype='str')

In [38]:
socioeconomic.columns

Index(['Region', 'Province_Count', 'Region_Area', 'Population',
       'Population Density', 'Disposable Income per capita',
       'Total Tourism Flow', 'Foreign Tourism Flow', 'Median Income'],
      dtype='str')

In [23]:
outlets[["Customer_Rating", "Review_Count", "Latitude", "Longitude"]].dtypes

Customer_Rating    float64
Review_Count         int64
Latitude           float64
Longitude          float64
dtype: object

In [24]:
outlets[[
    "Region",
    "Province",
    "City",
    "Price_Range_Cleaned",
    "Customer_Rating",
    "Review_Count",
    "Latitude",
    "Longitude"
]].isna().sum()

Region                 0
Province               0
City                   0
Price_Range_Cleaned    0
Customer_Rating        0
Review_Count           0
Latitude               0
Longitude              0
dtype: int64

In [25]:
regional_qsr = outlets.groupby("Region").agg(
    Outlet_Count=("Outlet ID", "count"),
    Average_Rating=("Customer_Rating", "mean"),
    Average_Review_Count=("Review_Count", "mean")
).reset_index()

regional_qsr

                   Region  Outlet_Count  Average_Rating  Average_Review_Count
0                 Abruzzo            56        3.941071           1351.732143
1              Basilicata             4        3.575000           1387.250000
2                Calabria            34        4.188235           1443.411765
3                Campania           125        3.810400           1817.952000
4          Emilia-Romagna           244        3.807377           3114.061475
5   Friuli-Venezia Giulia            50        3.848000           1660.840000
6                   Lazio           414        4.004831           1794.391304
7                 Liguria            65        3.847692           2532.553846
8               Lombardia           799        3.829412           1625.804756
9                  Marche            63        3.857143           1866.603175
10                 Molise             3        4.033333           1138.000000
11               Piemonte           252        3.826190           1678.940476
12                 Puglia            62        4.072581           2091.225806
13               Sardegna            54        4.046296           1340.296296
14                Sicilia           104        3.895192           1473.086538
15                Toscana           177        3.848023           1976.847458
16    Trentino-Alto Adige            31        3.729032           2592.774194
17                 Umbria            30        3.946667           1761.033333
18          Valle d'Aosta             5        3.800000           1480.200000
19                 Veneto           244        3.811475           1772.545082

In [26]:
regional_analysis = regional_qsr.merge(
    socioeconomic,
    on="Region",
    how="left"
)

regional_analysis.head()

,Region,Outlet_Count,Average_Rating,Average_Review_Count,Province_Count,Region_Area,Population,Population Density,Disposable Income per capita,Total Tourism Flow,Foreign Tourism Flow,Median Income
0,Abruzzo,56,3.941071,1351.732143,4,10831.84,1267222,117.0,19768,6804820.0,978924.0,24767
1,Basilicata,4,3.575000,1387.250000,2,10073.32,525281,52.1,17336,2537324.0,428180.0,24984
2,Calabria,34,4.188235,1443.411765,5,15221.90,1827571,120.1,16173,8100594.0,1486391.0,22225
3,Campania,125,3.810400,1817.952000,5,13670.95,5568703,407.3,16445,20695842.0,10601880.0,23751
4,Emilia-Romagna,244,3.807377,3114.061475,9,22452.78,4477009,199.4,26072,39176137.0,11087454.0,35682

In [27]:
regional_analysis["Outlets_per_100k_people"] = (
    regional_analysis["Outlet_Count"] / regional_analysis["Population"] * 100000
)

regional_analysis.head()

,Region,Outlet_Count,Average_Rating,Average_Review_Count,Province_Count,Region_Area,Population,Population Density,Disposable Income per capita,Total Tourism Flow,Foreign Tourism Flow,Median Income,Outlets_per_100k_people
0,Abruzzo,56,3.941071,1351.732143,4,10831.84,1267222,117.0,19768,6804820.0,978924.0,24767,4.419115
1,Basilicata,4,3.575000,1387.250000,2,10073.32,525281,52.1,17336,2537324.0,428180.0,24984,0.761497
2,Calabria,34,4.188235,1443.411765,5,15221.90,1827571,120.1,16173,8100594.0,1486391.0,22225,1.860393
3,Campania,125,3.810400,1817.952000,5,13670.95,5568703,407.3,16445,20695842.0,10601880.0,23751,2.244688
4,Emilia-Romagna,244,3.807377,3114.061475,9,22452.78,4477009,199.4,26072,39176137.0,11087454.0,35682,5.450067

In [28]:
regional_analysis = regional_analysis[[
    "Region",
    "Outlet_Count",
    "Population",
    "Outlets_per_100k_people",
    "Average_Rating",
    "Average_Review_Count",
    "Disposable Income per capita",
    "Total Tourism Flow",
    "Population Density",
    "Median Income"
]]

regional_analysis

,Region,Outlet_Count,Population,Outlets_per_100k_people,Average_Rating,Average_Review_Count,Disposable Income per capita,Total Tourism Flow,Population Density,Median Income
0,Abruzzo,56,1267222,4.419115,3.941071,1351.732143,19768,6804820.0,117.0,24767
1,Basilicata,4,525281,0.761497,3.575000,1387.250000,17336,2537324.0,52.1,24984
2,Calabria,34,1827571,1.860393,4.188235,1443.411765,16173,8100594.0,120.1,22225
3,Campania,125,5568703,2.244688,3.810400,1817.952000,16445,20695842.0,407.3,23751
4,Emilia-Romagna,244,4477009,5.450067,3.807377,3114.061475,26072,39176137.0,199.4,35682
5,Friuli-Venezia Giulia,50,1193496,4.189373,3.848000,1660.840000,23494,9946875.0,151.8,30856
6,Lazio,414,5709444,7.251144,4.004831,1794.391304,23348,45727169.0,331.3,28714
7,Liguria,65,1511988,4.298976,3.847692,2532.553846,25085,16084210.0,279.2,28085
8,Lombardia,799,10065694,7.937853,3.829412,1625.804756,27243,41795073.0,421.8,32485
9,Marche,63,1479832,4.257240,3.857143,1866.603175,22116,10660677.0,157.4,33315
10,Molise,3,285940,1.049171,4.033333,1138.000000,18212,494786.0,64.1,24484
11,Piemonte,252,4255006,5.922436,3.826190,1678.940476,24416,14410448.0,167.6,30267
12,Puglia,62,3865277,1.604025,4.072581,2091.225806,17148,16822144.0,197.8,26702
13,Sardegna,54,1554490,3.473808,4.046296,1340.296296,19064,14200536.0,64.5,24459
14,Sicilia,104,4775194,2.177922,3.895192,1473.086538,16907,16448284.0,184.9,22810
15,Toscana,177,3659222,4.837094,3.848023,1976.847458,23494,46019310.0,159.2,33268
16,Trentino-Alto Adige,31,1090818,2.841904,3.729032,2592.774194,28130,55227131.0,80.2,37563
17,Umbria,30,850627,3.526810,3.946667,1761.033333,21636,6428948.0,100.5,33677
18,Valle d'Aosta,5,122554,4.079834,3.800000,1480.200000,25152,3692878.0,37.6,32900
19,Veneto,244,4857460,5.023201,3.811475,1772.545082,24103,71896863.0,263.9,32272

In [29]:
regional_analysis.sort_values(
    "Outlet_Count",
    ascending=False
)[["Region", "Outlet_Count"]]

                   Region  Outlet_Count
8               Lombardia           799
6                   Lazio           414
11               Piemonte           252
4          Emilia-Romagna           244
19                 Veneto           244
15                Toscana           177
3                Campania           125
14                Sicilia           104
7                 Liguria            65
9                  Marche            63
12                 Puglia            62
0                 Abruzzo            56
13               Sardegna            54
5   Friuli-Venezia Giulia            50
2                Calabria            34
16    Trentino-Alto Adige            31
17                 Umbria            30
18          Valle d'Aosta             5
1              Basilicata             4
10                 Molise             3

### Regional Ranking by Total Outlet Count

The ranking by total outlet count shows the absolute distribution of QSR outlets across Italian regions. Lombardia has the highest number of outlets, followed by Lazio, Piemonte, Veneto, and Emilia-Romagna.

This result suggests that QSR outlets are most concentrated in larger and economically important regions, especially those containing major urban areas such as Milano, Roma, Torino, Venezia, and Bologna. However, this ranking only shows the absolute number of outlets and does not account for differences in regional population size. For this reason, the next step is to compare these results with outlets per 100,000 people.

In [30]:
regional_analysis.sort_values(
    "Outlets_per_100k_people",
    ascending=False
)[["Region", "Outlets_per_100k_people"]]

                   Region  Outlets_per_100k_people
8               Lombardia                 7.937853
6                   Lazio                 7.251144
11               Piemonte                 5.922436
4          Emilia-Romagna                 5.450067
19                 Veneto                 5.023201
15                Toscana                 4.837094
0                 Abruzzo                 4.419115
7                 Liguria                 4.298976
9                  Marche                 4.257240
5   Friuli-Venezia Giulia                 4.189373
18          Valle d'Aosta                 4.079834
17                 Umbria                 3.526810
13               Sardegna                 3.473808
16    Trentino-Alto Adige                 2.841904
3                Campania                 2.244688
14                Sicilia                 2.177922
2                Calabria                 1.860393
12                 Puglia                 1.604025
10                 Molise                 1.049171
1              Basilicata                 0.761497

### Regional Ranking by Outlets Per 100,000 People

The outlets per 100,000 people ranking shows the relative concentration of QSR outlets after adjusting for regional population size. Lombardia and Lazio remain the two highest-ranking regions, meaning that their high outlet numbers are not only due to large populations but also reflect a relatively strong QSR presence per resident.

Piemonte, Emilia-Romagna, and Veneto also remain among the highest-ranked regions. This suggests that QSR outlet concentration is strongest in several northern and central regions with large urban centers, strong commercial activity, and important transport or tourism flows.

Compared with the raw outlet count ranking, the per-capita ranking provides a fairer comparison across regions because it accounts for population size.

In [31]:
ranking_comparison = regional_analysis[[
    "Region",
    "Outlet_Count",
    "Outlets_per_100k_people"
]].sort_values(
    "Outlet_Count",
    ascending=False
)

ranking_comparison

                   Region  Outlet_Count  Outlets_per_100k_people
8               Lombardia           799                 7.937853
6                   Lazio           414                 7.251144
11               Piemonte           252                 5.922436
4          Emilia-Romagna           244                 5.450067
19                 Veneto           244                 5.023201
15                Toscana           177                 4.837094
3                Campania           125                 2.244688
14                Sicilia           104                 2.177922
7                 Liguria            65                 4.298976
9                  Marche            63                 4.257240
12                 Puglia            62                 1.604025
0                 Abruzzo            56                 4.419115
13               Sardegna            54                 3.473808
5   Friuli-Venezia Giulia            50                 4.189373
2                Calabria            34                 1.860393
16    Trentino-Alto Adige            31                 2.841904
17                 Umbria            30                 3.526810
18          Valle d'Aosta             5                 4.079834
1              Basilicata             4                 0.761497
10                 Molise             3                 1.049171

### Comparison of Raw and Per-Capita Outlet Distribution

The comparison table shows both the absolute number of QSR outlets and the normalized outlet concentration per 100,000 people. Lombardia and Lazio rank highest in both measures, indicating that they have both a large number of outlets and a high outlet concentration relative to population.

smaller regions, such as Valle d'Aosta, have very low outlet counts in absolute terms but a higher per-capita value because their population is small.

so the comparison suggests that QSR distribution is partly related to population size, but the per-capita measure gives a clearer view of relative regional concentration.

In [32]:
per_capita_comparison = regional_analysis[[
    "Region",
    "Outlet_Count",
    "Population",
    "Outlets_per_100k_people"
]].sort_values(
    "Outlets_per_100k_people",
    ascending=False
)

per_capita_comparison

                   Region  Outlet_Count  Population  Outlets_per_100k_people
8               Lombardia           799    10065694                 7.937853
6                   Lazio           414     5709444                 7.251144
11               Piemonte           252     4255006                 5.922436
4          Emilia-Romagna           244     4477009                 5.450067
19                 Veneto           244     4857460                 5.023201
15                Toscana           177     3659222                 4.837094
0                 Abruzzo            56     1267222                 4.419115
7                 Liguria            65     1511988                 4.298976
9                  Marche            63     1479832                 4.257240
5   Friuli-Venezia Giulia            50     1193496                 4.189373
18          Valle d'Aosta             5      122554                 4.079834
17                 Umbria            30      850627                 3.526810
13               Sardegna            54     1554490                 3.473808
16    Trentino-Alto Adige            31     1090818                 2.841904
3                Campania           125     5568703                 2.244688
14                Sicilia           104     4775194                 2.177922
2                Calabria            34     1827571                 1.860393
12                 Puglia            62     3865277                 1.604025
10                 Molise             3      285940                 1.049171
1              Basilicata             4      525281                 0.761497

### Per-Capita Ranking With Population Context

This table ranks regions by QSR outlets per 100,000 people while also showing the original outlet count and regional population. Adding population makes it easier to understand why some regions move differently in the normalized ranking.

Lombardia and Lazio remain at the top because they have both large outlet counts and high outlet concentration relative to their populations. Valle d'Aosta has only 5 outlets, but its small population gives it a relatively high per-capita value. In contrast, regions such as Campania, Sicilia, and Puglia have larger populations but lower outlets per 100,000 people, which suggests a lower relative QSR concentration.

### Summary of Regional Analysis

The regional analysis shows that QSR outlets are unevenly distributed across Italian regions. Lombardia and Lazio have the highest number of outlets in absolute terms, and they also remain the highest after normalizing by population. This suggests that these regions have both strong absolute QSR presence and high outlet concentration relative to their populations.

The per-capita indicator is important because it allows regions with different population sizes to be compared more fairly. Some smaller regions, such as Valle d'Aosta, have low outlet counts but relatively high outlets per 100,000 people because of their smaller population base. Meanwhile, some larger southern regions have lower per-capita values, suggesting a weaker relative concentration of QSR outlets.

Overall, the results suggest that QSR distribution is concentrated in larger, economically important regions, especially those with major urban centers and commercial activity. This regional table will provide the basis for later spatial mapping, correlation analysis, and regression analysis.